# Generated by Django 5.2.10 on 2026-02-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_external_id'),
        ('mcp', '0002_tool_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tool name (e.g., "create_sales_lead")', max_length=100)),
                ('description', models.TextField(help_text='Human-readable description')),
                ('llm_description', models.CharField(blank=True, help_text='Short description optimized for AI agents', max_length=300)),
                ('tool_hints', models.TextField(blank=True, help_text='Usage hints for AI agents')),
                ('examples', models.JSONField(blank=True, default=list, help_text='Example inputs and outputs for LLM context')),
                ('maps_to_system', models.CharField(help_text='System alias (e.g., "salesforce")', max_length=100)),
                ('maps_to_action', models.CharField(help_text='Full action path (e.g., "contact_create" or "rest.contact.create")', max_length=200)),
                ('input_schema', models.JSONField(default=dict, help_text='JSON Schema for business-level input parameters')),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema for output (optional)')),
                ('field_mapping', models.JSONField(default=dict, help_text='Maps business fields to API fields. Values can be field names or expressions.')),
                ('defaults', models.JSONField(blank=True, default=dict, help_text='Default values for API fields not exposed to business tool')),
                ('output_mapping', models.JSONField(blank=True, default=dict, help_text='Maps API response fields to business-level output')),
                ('tool_type', models.CharField(choices=[('read', 'Read (Safe)'), ('write', 'Write (Requires Power)'), ('action', 'Action (Transactional)')], default='read', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_confirmation', models.BooleanField(default=False, help_text='If true, agent should confirm before executing')),
                ('supports_rollback', models.BooleanField(default=False, help_text='If true, this action can be undone')),
                ('rollback_action', models.CharField(blank=True, help_text='Action to call for rollback (if different from inverse)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Tool',
                'verbose_name_plural': 'Business Tools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g., "Sales Operations Pack")', max_length=200)),
                ('alias', models.SlugField(help_text='Unique identifier (e.g., "sales-ops")', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this pack provides')),
                ('vertical', models.CharField(choices=[('general', 'General'), ('sales', 'Sales Operations'), ('marketing', 'Marketing'), ('finance', 'Finance Operations'), ('hr', 'Human Resources'), ('construction', 'Construction'), ('healthcare', 'Healthcare'), ('legal', 'Legal'), ('custom', 'Custom')], default='general', max_length=50)),
                ('llm_description', models.CharField(blank=True, help_text='Short description optimized for AI agents', max_length=500)),
                ('use_cases', models.JSONField(blank=True, default=list, help_text='List of example use cases for AI context')),
                ('is_active', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=False, help_text='If true, available to all accounts')),
                ('requires_systems', models.JSONField(blank=True, default=list, help_text='List of system aliases required for this pack')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capability Pack',
                'verbose_name_plural': 'Capability Packs',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='mcpauditlog',
            new_name='mcp_mcpaudi_account_b7b7dc_idx',
            old_name='mcp_mcpaudi_account_a90d65_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpauditlog',
            new_name='mcp_mcpaudi_account_ece135_idx',
            old_name='mcp_mcpaudi_account_3a8c2e_idx',
        ),
        migrations.AddField(
            model_name='capabilitypack',
            name='account',
            field=models.ForeignKey(blank=True, help_text='If null, this is a global pack available to all accounts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capability_packs', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='businesstool',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_tools', to='mcp.capabilitypack'),
        ),
        migrations.AlterUniqueTogether(
            name='capabilitypack',
            unique_together={('account', 'alias')},
        ),
        migrations.AlterUniqueTogether(
            name='businesstool',
            unique_together={('pack', 'name')},
        ),
    ]
