# Generated by Django 5.2.10 on 2026-02-09 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_external_id'),
        ('mcp', '0003_capability_packs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpauditlog',
            name='context_summary',
            field=models.TextField(blank=True, help_text='Summary of conversation/task context leading to this action'),
        ),
        migrations.AddField(
            model_name='mcpauditlog',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Groups related audit entries together', max_length=100),
        ),
        migrations.AddField(
            model_name='mcpauditlog',
            name='intent',
            field=models.CharField(blank=True, help_text='High-level intent of this action (e.g., "Retrieve customer data")', max_length=500),
        ),
        migrations.AddField(
            model_name='mcpauditlog',
            name='is_reversible',
            field=models.BooleanField(default=False, help_text='Whether this action can be rolled back'),
        ),
        migrations.AddField(
            model_name='mcpauditlog',
            name='parent_audit_id',
            field=models.IntegerField(blank=True, help_text='ID of parent audit entry (for nested operations)', null=True),
        ),
        migrations.AddField(
            model_name='mcpauditlog',
            name='reasoning',
            field=models.TextField(blank=True, help_text='AI agent reasoning for this action (optional, from agent context)'),
        ),
        migrations.AddField(
            model_name='mcpauditlog',
            name='rollback_audit_id',
            field=models.IntegerField(blank=True, help_text='ID of the audit log entry for the rollback action', null=True),
        ),
        migrations.AddField(
            model_name='mcpauditlog',
            name='rollback_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data needed to reverse this action'),
        ),
        migrations.AddField(
            model_name='mcpauditlog',
            name='rolled_back',
            field=models.BooleanField(default=False, help_text='Whether this action has been rolled back'),
        ),
        migrations.AddField(
            model_name='mcpauditlog',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, help_text='When this action was rolled back', null=True),
        ),
        migrations.AlterField(
            model_name='mcpauditlog',
            name='tool_type',
            field=models.CharField(choices=[('workflow', 'Workflow Tool'), ('system_read', 'System Tool (Read)'), ('system_write', 'System Tool (Write)'), ('resource', 'Resource Access'), ('context', 'Context Tool'), ('analyzer', 'Analyzer Tool')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='mcpauditlog',
            index=models.Index(fields=['correlation_id'], name='mcp_mcpaudi_correla_7655db_idx'),
        ),
    ]
