# Generated by Django 5.2.10 on 2026-02-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_external_id'),
        ('mcp', '0004_audit_reasoning_rollback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('include_tools', models.JSONField(blank=True, default=list, help_text='Specific tool names to include (in addition to categories)')),
                ('exclude_tools', models.JSONField(blank=True, default=list, help_text='Specific tool names to exclude (even if category allows)')),
                ('mode', models.CharField(choices=[('safe', 'Safe Mode'), ('power', 'Power Mode')], default='safe', help_text='Safe mode blocks write operations, Power mode allows all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to='accounts.account')),
                ('allowed_categories', models.ManyToManyField(blank=True, help_text='Categories this profile can access. Empty = all categories allowed.', related_name='profiles', to='mcp.toolcategory')),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
                'ordering': ['name'],
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.AddField(
            model_name='mcpapikey',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Agent profile defining tool access. If set, overrides mode/allowed_tools/blocked_tools.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='mcp.agentprofile'),
        ),
    ]
