# Generated by Django 5.2.10 on 2026-02-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_external_id'),
        ('mcp', '0005_add_agent_profile'),
    ]

    operations = [
        # Create Project model
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(db_index=True, help_text='URL-safe identifier for the project', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('external_mappings', models.JSONField(blank=True, default=dict, help_text='Maps system aliases to external project identifiers')),
                ('allowed_categories', models.JSONField(blank=True, help_text='List of allowed category keys. Null = no restriction.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_projects', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
                'unique_together': {('account', 'slug')},
            },
        ),
        # Create ProjectMapping model
        migrations.CreateModel(
            name='ProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_alias', models.CharField(help_text='System alias (e.g., "jira", "github")', max_length=100)),
                ('external_id', models.CharField(help_text='External project identifier in the system', max_length=500)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional configuration for this mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='mcp.project')),
            ],
            options={
                'verbose_name': 'Project Mapping',
                'verbose_name_plural': 'Project Mappings',
                'ordering': ['system_alias'],
                'unique_together': {('project', 'system_alias')},
            },
        ),
        # Add project field to MCPApiKey
        migrations.AddField(
            model_name='mcpapikey',
            name='project',
            field=models.ForeignKey(
                blank=True,
                help_text='Project this token is bound to. If set, all operations are scoped to this project.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='api_keys',
                to='mcp.project'
            ),
        ),
        # Add is_admin field to MCPApiKey
        migrations.AddField(
            model_name='mcpapikey',
            name='is_admin',
            field=models.BooleanField(
                default=False,
                help_text='Admin tokens can use X-Project-Id header to access any project'
            ),
        ),
    ]
