# Generated by Django 5.2.10 on 2026-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0006_add_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpauditlog',
            name='tool_type',
            field=models.CharField(choices=[('system_read', 'System Tool (Read)'), ('system_write', 'System Tool (Write)'), ('resource', 'Resource Access'), ('context', 'Context Tool'), ('analyzer', 'Analyzer Tool')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projectpolicy',
            name='project_identifier',
            field=models.CharField(help_text='Project identifier (e.g., "PROJ-*")', max_length=255),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='key',
            field=models.CharField(db_index=True, help_text='Unique identifier for the category (e.g., "crm.read", "system.write")', max_length=100),
        ),
    ]
