# Generated by Django 5.2.10 on 2026-02-16 23:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_external_id'),
        ('mcp', '0007_alter_mcpauditlog_tool_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_alias', models.CharField(db_index=True, max_length=100)),
                ('tool_name', models.CharField(db_index=True, max_length=255)),
                ('action_name', models.CharField(blank=True, max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField()),
                ('error_data', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(choices=[('auth_expired', 'Auth Expired'), ('auth_invalid', 'Auth Invalid'), ('auth_permissions', 'Auth Permissions'), ('not_found_mapping', 'Not Found (Mapping)'), ('not_found_path', 'Not Found (Path)'), ('validation_missing', 'Validation (Missing Fields)'), ('validation_type', 'Validation (Type Error)'), ('rate_limit', 'Rate Limit'), ('server_error', 'Server Error'), ('timeout', 'Timeout'), ('connection', 'Connection Error'), ('unknown', 'Unknown')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('diagnosis_summary', models.CharField(max_length=500)),
                ('diagnosis_detail', models.TextField(blank=True)),
                ('has_fix', models.BooleanField(default=False)),
                ('fix_description', models.TextField(blank=True)),
                ('fix_action', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dismissed', 'Dismissed'), ('applied', 'Applied'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_diagnostics', to='accounts.account')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['account', 'system_alias', 'category', 'status'], name='mcp_errordi_account_1d44ff_idx'), models.Index(fields=['account', 'created_at'], name='mcp_errordi_account_11865b_idx')],
            },
        ),
    ]
