# Generated by Django 5.2.10 on 2026-02-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0008_errordiagnostic'),
        ('systems', '0045_accountsystem_project_scoping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_source', models.CharField(choices=[('account', 'Account (shared)'), ('project', 'Project-specific')], default='account', help_text='Where to look for credentials: shared account-level or project-specific', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='External project identifier in the target system (e.g., Jira "PROJ-123")', max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('custom_config', models.JSONField(blank=True, default=dict, help_text='Additional integration-specific configuration')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='mcp.project')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_integrations', to='systems.system')),
            ],
            options={
                'verbose_name': 'Project Integration',
                'verbose_name_plural': 'Project Integrations',
                'ordering': ['system__alias'],
                'unique_together': {('project', 'system')},
            },
        ),
    ]
