# Generated by Django 5.2.10 on 2026-02-18 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0010_data_create_default_projects_and_integrations'),
        ('systems', '0045_accountsystem_project_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='entity_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='systems.entitymapping'),
        ),
    ]
