# Generated by Django 5.2.10 on 2026-02-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0011_project_entity_mapping_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectintegration',
            name='allowed_actions',
            field=models.JSONField(blank=True, help_text="List of allowed tool names (e.g. ['aiforsite_images_list']). Null = all tools allowed.", null=True),
        ),
    ]
