# Generated by Django 5.2.10 on 2026-02-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0012_projectintegration_allowed_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='entity_mapping',
        ),
        migrations.DeleteModel(
            name='ProjectMapping',
        ),
    ]
