# Generated by Django 5.2.11 on 2026-03-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0017_remove_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='include_tools',
            field=models.JSONField(blank=True, default=list, help_text='Allowed tool names. Empty list = all tools allowed.'),
        ),
    ]
