# Generated by Django 4.2.24 on 2025-09-24 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountuser',
            unique_together={('account', 'user')},
        ),
    ]
