# Generated by Django 4.2.24 on 2025-09-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountuser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='is_current_active',
            field=models.BooleanField(default=False),
        ),
    ]
