# Generated by Django 5.2.10 on 2026-02-06 11:06
# Modified: removed clients app dependency and created_by_client_app field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='External identifier for MCP project mapping', max_length=255, null=True, unique=True),
        ),
    ]
