# Generated by Django 5.2.10 on 2026-02-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_external_id'),
        ('mcp', '0009_add_projectintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_project',
            field=models.ForeignKey(blank=True, help_text='Default project for new tokens. Auto-set when first project is created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mcp.project'),
        ),
    ]
