# Generated by Django 5.2.11 on 2026-03-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_unique_active_account_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.CharField(db_index=True, help_text='Public gateway identifier (e.g., gw_abc123)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('secret_hash', models.CharField(help_text='SHA-256 hash of the gateway secret', max_length=128)),
                ('secret_prefix', models.CharField(help_text='First 10 chars for lookup', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Registration'), ('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_spec_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_key_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_audit_push_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('active_sessions', models.IntegerField(default=0)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('credential_status', models.JSONField(blank=True, default=dict, help_text='{"system_alias": true/false} — whether gateway has credentials for each system')),
                ('registration_token', models.CharField(blank=True, help_text='One-time token for gateway registration (cleared after use)', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='accounts.account')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='GatewayAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=255)),
                ('tool_type', models.CharField(max_length=50)),
                ('duration_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_category', models.CharField(blank=True, max_length=30)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('mode', models.CharField(default='safe', max_length=20)),
                ('gateway_timestamp', models.DateTimeField(help_text='When the event occurred on the gateway')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_audit_logs', to='accounts.account')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='gateways.gateway')),
            ],
            options={
                'ordering': ['-gateway_timestamp'],
                'indexes': [models.Index(fields=['account', 'gateway_timestamp'], name='gateways_ga_account_deaee3_idx'), models.Index(fields=['gateway', 'gateway_timestamp'], name='gateways_ga_gateway_df7d6f_idx')],
            },
        ),
    ]
