"""
Django settings for Adapterly project (production-ready).

Generated by 'django-admin startproject' using Django 4.2.24.
"""

import json
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# -------------------------------------------------
# Paths
# -------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------------------------
# Core security & debug
# -------------------------------------------------
def env_bool(name: str, default: bool = False) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return str(val).lower() in {"1", "true", "yes", "on"}


SECRET_KEY = os.getenv("SECRET_KEY", "!!!-CHANGE-ME-IN-PRODUCTION-!!!")
DEBUG = env_bool("DEBUG", False)
if not DEBUG and SECRET_KEY.startswith("!!!"):
    raise RuntimeError("SECRET_KEY must be set in production — refusing to start with the default value.")

# comma-separated hosts in .env, fallback to our known hosts
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]

# CSRF trusted origins (required for HTTPS domain in Django 4+)
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "https://localhost").split(",") if o.strip()
]

# -------------------------------------------------
# Applications
# -------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    # DRF
    "rest_framework",
    "django_filters",
    # local apps - Adapterly MCP Tool Gateway
    "apps.accounts",
    "apps.systems",
    "apps.core",
    "apps.mcp",
    "apps.help",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.core.middleware.LoginRateLimitMiddleware",  # Rate limit login attempts
    "apps.accounts.middleware.ActiveAccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

# allauth (new API)
ACCOUNT_EMAIL_VERIFICATION = os.getenv("ACCOUNT_EMAIL_VERIFICATION", "mandatory")
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True  # Skip the signup form for social logins
SOCIALACCOUNT_LOGIN_ON_GET = True  # Skip the "Sign In" confirmation page
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"  # Don't require email verification for social accounts
SOCIALACCOUNT_QUERY_EMAIL = True  # Request email from provider
SOCIALACCOUNT_STORE_TOKENS = False  # Don't store OAuth tokens (we don't need them)
SOCIALACCOUNT_ADAPTER = "apps.accounts.adapters.CustomSocialAccountAdapter"  # Custom adapter for smooth signup

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "VERIFIED_EMAIL": True,  # Trust Google's email verification
    }
}

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.app_name",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
SITE_ID = int(os.getenv("SITE_ID", "1"))

# -------------------------------------------------
# Database (SQLite by default; switch to Postgres in prod)
# -------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.getenv("DB_NAME", str(BASE_DIR / "db.sqlite3")),
        "USER": os.getenv("DB_USER", ""),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", ""),
        "PORT": os.getenv("DB_PORT", ""),
    }
}

# -------------------------------------------------
# Password validation
# -------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 10}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------
# I18N / TZ
# -------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = os.getenv("TIME_ZONE", "Europe/Helsinki")
USE_I18N = True
USE_TZ = True

# -------------------------------------------------
# Static files
# -------------------------------------------------
STATIC_URL = "/static/"

# collectstatic destination (served by Nginx/Apache in production)
STATIC_ROOT = os.getenv("STATIC_ROOT", str(BASE_DIR / "staticfiles"))

# Source directories for static files (collected by collectstatic)
# Project-level static files: BASE_DIR / "static"
# App-level static files are automatically discovered
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Projektitason staattiset tiedostot
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
APPEND_SLASH = True

# -------------------------------------------------
# DRF
# -------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # Rate limiting
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",  # Unauthenticated users
        "user": "1000/hour",  # Authenticated users
        "login": "5/minute",  # Login attempts
        "mcp_call": "1000/hour",  # MCP tool calls
    },
}

# CSRF & cookies
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = True

# -------------------------------------------------
# HTTPS hardening (kun käytössä TLS Nginxillä, suositeltavaa)
# -------------------------------------------------
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", True)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", True)
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", True)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", True)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True

# Upload size limits (10 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760

# -------------------------------------------------
# Object Storage (S3-compatible) — optional
# -------------------------------------------------
OBJECT_STORAGE_ENABLED = os.getenv("OBJECT_STORAGE_ENABLED", "false").lower() == "true"
OBJECT_STORAGE_ENDPOINT = os.getenv("OBJECT_STORAGE_ENDPOINT", "")
OBJECT_STORAGE_ACCESS_KEY = os.getenv("OBJECT_STORAGE_ACCESS_KEY", "")
OBJECT_STORAGE_SECRET_KEY = os.getenv("OBJECT_STORAGE_SECRET_KEY", "")
OBJECT_STORAGE_BUCKET = os.getenv("OBJECT_STORAGE_BUCKET", "workflow-tables")
OBJECT_STORAGE_REGION = os.getenv("OBJECT_STORAGE_REGION", "eu-central")

# -------------------------------------------------
# Email
# -------------------------------------------------
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@adapterly.io")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Adapter update notifications
ADAPTER_UPDATE_NOTIFY_EMAILS = json.loads(os.getenv("ADAPTER_UPDATE_NOTIFY_EMAILS", "[]"))

# -------------------------------------------------
# App Branding
# -------------------------------------------------
APP_NAME = os.getenv("APP_NAME", "Adapterly")
APP_LOGO_URL = os.getenv("APP_LOGO_URL", "")  # URL to logo image, empty = use icon
APP_TAGLINE = os.getenv("APP_TAGLINE", "AI integration platform for construction & logistics")
APP_PRIMARY_COLOR = os.getenv("APP_PRIMARY_COLOR", "#667eea")
APP_SECONDARY_COLOR = os.getenv("APP_SECONDARY_COLOR", "#764ba2")

# -------------------------------------------------
# Logging
# -------------------------------------------------
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO" if not DEBUG else "DEBUG")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} {asctime} {module}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "apps": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "apps.mcp": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "apps.systems": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# -------------------------------------------------
# MCP (Model Context Protocol) Settings
# -------------------------------------------------
# Default mode for MCP sessions (safe or power)
MCP_DEFAULT_MODE = os.getenv("MCP_DEFAULT_MODE", "safe")

# Rate limiting for MCP API calls (per session per hour)
MCP_RATE_LIMIT_PER_HOUR = int(os.getenv("MCP_RATE_LIMIT_PER_HOUR", "1000"))

# Audit log retention (days, 0 = forever)
MCP_AUDIT_LOG_RETENTION_DAYS = int(os.getenv("MCP_AUDIT_LOG_RETENTION_DAYS", "90"))

# Session timeout (seconds, 0 = no timeout)
MCP_SESSION_TIMEOUT = int(os.getenv("MCP_SESSION_TIMEOUT", "3600"))

# Browser automation settings for XHR sessions
MCP_BROWSER_HEADLESS = os.getenv("MCP_BROWSER_HEADLESS", "true").lower() == "true"
MCP_BROWSER_TIMEOUT = int(os.getenv("MCP_BROWSER_TIMEOUT", "30000"))  # milliseconds
