# Generated by Django 4.2.24 on 2025-09-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_infrakit_auth_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='alias',
            field=models.CharField(blank=True, help_text="Unique alias used in workflow DSL (e.g., 'jira', 'slack')", max_length=50, null=True, unique=True),
        ),
    ]
