# Generated by Django 4.2.24 on 2025-10-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_make_alias_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsystem',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='systemendpoint',
            name='auth_config',
        ),
        migrations.RemoveField(
            model_name='systemendpoint',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='systemendpoint',
            name='base_url',
        ),
        migrations.AddField(
            model_name='authenticationstep',
            name='base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='systemendpoint',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='systemendpoint',
            name='path_template',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
