# Generated by Django 4.2.24 on 2025-10-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_remove_accountsystem_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemendpoint',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('api_key', 'API Key'), ('oauth2', 'OAuth 2.0'), ('basic', 'Basic Authentication'), ('bearer', 'Bearer Token'), ('custom', 'Custom')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='systemendpoint',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10),
        ),
    ]
