# Generated by Django 4.2.24 on 2025-10-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_systemendpoint_auth_type_systemendpoint_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=120)),
                ('type', models.CharField(choices=[('API', 'API'), ('XHR', 'XHR')], max_length=8)),
                ('base_url', models.CharField(blank=True, default='', max_length=300)),
                ('auth', models.JSONField(blank=True, default=dict)),
                ('requires_browser', models.BooleanField(default=False)),
                ('browser', models.JSONField(blank=True, default=dict)),
                ('rate_limits', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='system',
            name='schema_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='system',
            name='variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='systems.interface')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='systems.system')),
            ],
            options={
                'unique_together': {('system', 'name')},
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='systems.system'),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('system', 'name')},
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=8)),
                ('path', models.CharField(max_length=400)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('parameters_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('pagination', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='systems.resource')),
            ],
            options={
                'unique_together': {('resource', 'name')},
            },
        ),
    ]
