# Generated by Django 4.2.24 on 2025-10-06 14:35

from django.db import migrations, models


def backfill_aliases(apps, schema_editor):
    System = apps.get_model('systems', 'System')
    Interface = apps.get_model('systems', 'Interface')
    Resource = apps.get_model('systems', 'Resource')
    Action = apps.get_model('systems', 'Action')

    # Interface: default alias = name; ensure uniqueness per system
    for interface in Interface.objects.all():
        base = (interface.name or '').strip() or 'interface'
        alias = base
        n = 1
        while Interface.objects.filter(system=interface.system, alias=alias).exclude(pk=interface.pk).exists():
            n += 1
            alias = f"{base}-{n}"
        interface.alias = alias
        interface.save(update_fields=['alias'])

    # Resource: default alias = name; ensure uniqueness per system
    for resource in Resource.objects.all():
        base = (resource.name or '').strip() or 'resource'
        alias = base
        n = 1
        while Resource.objects.filter(system=resource.system, alias=alias).exclude(pk=resource.pk).exists():
            n += 1
            alias = f"{base}-{n}"
        resource.alias = alias
        resource.save(update_fields=['alias'])

    # Action: default alias = name; ensure uniqueness per resource
    for action in Action.objects.all():
        base = (action.name or '').strip() or 'action'
        alias = base
        n = 1
        while Action.objects.filter(resource=action.resource, alias=alias).exclude(pk=action.pk).exists():
            n += 1
            alias = f"{base}-{n}"
        action.alias = alias
        action.save(update_fields=['alias'])


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_interface_system_meta_system_schema_digest_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='action',
            name='alias',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='interface',
            name='alias',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='resource',
            name='alias',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(backfill_aliases, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('resource', 'alias')},
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('system', 'alias')},
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('system', 'alias')},
        ),
        migrations.DeleteModel(
            name='SystemEndpoint',
        ),
    ]
