# Generated by Django 4.2.24 on 2025-10-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0013_alter_action_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('system', 'interface', 'alias')},
        ),
    ]
