# Generated by Django 4.2.24 on 2025-10-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_alter_resource_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('interface', 'alias')},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='system',
        ),
    ]
