# Generated by Django 4.2.24 on 2025-10-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0016_update_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsystem',
            name='session_cookie',
            field=models.TextField(blank=True, help_text='Session cookie (e.g., JSESSIONID) for XHR authentication'),
        ),
        migrations.AddField(
            model_name='accountsystem',
            name='csrf_token',
            field=models.CharField(blank=True, max_length=500, help_text='CSRF token for XHR requests'),
        ),
        migrations.AddField(
            model_name='accountsystem',
            name='session_expires_at',
            field=models.DateTimeField(blank=True, null=True, help_text='When the session expires'),
        ),
    ]
