# Generated by Django 4.2.25 on 2025-10-28 22:21

from django.db import migrations, models
import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0017_add_session_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsystem',
            name='api_key',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accountsystem',
            name='client_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accountsystem',
            name='client_secret',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accountsystem',
            name='csrf_token',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='CSRF token for XHR requests', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accountsystem',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountsystem',
            name='oauth_refresh_token',
            field=apps.core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountsystem',
            name='oauth_token',
            field=apps.core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountsystem',
            name='password',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accountsystem',
            name='session_cookie',
            field=apps.core.fields.EncryptedTextField(blank=True, help_text='Session cookie (e.g., JSESSIONID) for XHR authentication', null=True),
        ),
        migrations.AlterField(
            model_name='accountsystem',
            name='token',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='accountsystem',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
