# Generated by Django 4.2 on 2025-01-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('systems', '0022_infrakit_pagination'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='EntityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(help_text="Human-readable name, e.g. 'ACME Corporation'", max_length=255)),
                ('canonical_id', models.CharField(blank=True, help_text='Optional internal ID', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mappings', to='accounts.account')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='systems.entitytype')),
            ],
            options={
                'ordering': ['canonical_name'],
                'unique_together': {('account', 'entity_type', 'canonical_name')},
            },
        ),
        migrations.CreateModel(
            name='SystemEntityIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_value', models.CharField(help_text="The identifier in this system, e.g. 'PROJ', '001ABC'", max_length=500)),
                ('resource_hint', models.CharField(blank=True, help_text="Resource type hint, e.g. 'projects', 'accounts'", max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary identifier for this mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='systems.entitymapping')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_identifiers', to='systems.system')),
            ],
            options={
                'ordering': ['system__display_name'],
                'unique_together': {('mapping', 'system', 'identifier_value')},
            },
        ),
    ]
