# Generated by Django 4.2 on 2025-01-28
# Data migration to seed initial entity types

from django.db import migrations


def seed_entity_types(apps, schema_editor):
    EntityType = apps.get_model('systems', 'EntityType')

    entity_types = [
        {
            'name': 'project',
            'display_name': 'Project',
            'description': 'A project entity across systems (e.g., Jira project, GitHub repository)',
            'icon': 'folder',
        },
        {
            'name': 'user',
            'display_name': 'User',
            'description': 'A user/person entity across systems',
            'icon': 'person',
        },
        {
            'name': 'company',
            'display_name': 'Company',
            'description': 'A company/organization entity across systems (e.g., Salesforce Account)',
            'icon': 'building',
        },
        {
            'name': 'repository',
            'display_name': 'Repository',
            'description': 'A code repository across version control systems',
            'icon': 'git',
        },
        {
            'name': 'ticket',
            'display_name': 'Ticket',
            'description': 'A ticket/issue entity across systems',
            'icon': 'ticket',
        },
        {
            'name': 'contact',
            'display_name': 'Contact',
            'description': 'A contact/person entity in CRM systems',
            'icon': 'person-badge',
        },
        {
            'name': 'deal',
            'display_name': 'Deal',
            'description': 'A deal/opportunity entity in CRM systems',
            'icon': 'currency-dollar',
        },
    ]

    for entity_type in entity_types:
        EntityType.objects.get_or_create(
            name=entity_type['name'],
            defaults=entity_type
        )


def reverse_seed_entity_types(apps, schema_editor):
    EntityType = apps.get_model('systems', 'EntityType')
    EntityType.objects.filter(name__in=[
        'project', 'user', 'company', 'repository', 'ticket', 'contact', 'deal'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0023_add_entity_mapping_models'),
    ]

    operations = [
        migrations.RunPython(seed_entity_types, reverse_seed_entity_types),
    ]
