# Generated by Django 5.2.10 on 2026-02-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0026_add_sharepoint_adapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_mcp_enabled',
            field=models.BooleanField(default=True, help_text='If enabled, this action will be available as an MCP tool for AI agents'),
        ),
    ]
