# Generated by Django 4.2 on 2026-02-15
# Migration to add IndustryTemplate, TermMapping, and FieldMapping models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0028_add_action_is_mcp_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name, e.g. 'construction'", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Display name, e.g. 'Rakennusala'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='TermMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_term', models.CharField(help_text="Canonical term, e.g. 'project', 'site'", max_length=100)),
                ('system_term', models.CharField(help_text="Term in this system, e.g. 'Project', 'Projekti'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_mappings', to='systems.industrytemplate')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_mappings', to='systems.system')),
            ],
            options={
                'ordering': ['canonical_term', 'system__display_name'],
                'unique_together': {('template', 'canonical_term', 'system')},
            },
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_field', models.CharField(help_text="Canonical field name, e.g. 'project_id', 'start_date'", max_length=100)),
                ('system_field', models.CharField(help_text="Field name in this system, e.g. 'uuid', 'startDate'", max_length=100)),
                ('transform', models.CharField(blank=True, choices=[('', 'None'), ('uppercase', 'Uppercase'), ('lowercase', 'Lowercase'), ('date_iso', 'Date ISO format (YYYY-MM-DD)'), ('date_fi', 'Date Finnish format (DD.MM.YYYY)'), ('date_us', 'Date US format (MM/DD/YYYY)'), ('datetime_iso', 'Datetime ISO format'), ('boolean_01', 'Boolean as 0/1'), ('boolean_yn', 'Boolean as Y/N'), ('trim', 'Trim whitespace')], help_text='Optional transformation', max_length=50)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this field is required')),
                ('description', models.CharField(blank=True, help_text='Description of this field mapping', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='systems.industrytemplate')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='systems.entitytype')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='systems.system')),
            ],
            options={
                'ordering': ['entity_type__name', 'canonical_field', 'system__display_name'],
                'unique_together': {('template', 'entity_type', 'canonical_field', 'system')},
            },
        ),
    ]
