# Generated by Django 4.2 on 2026-02-15
# Data migration to seed construction industry entity types

from django.db import migrations


def seed_construction_entity_types(apps, schema_editor):
    """Add construction industry specific entity types."""
    EntityType = apps.get_model('systems', 'EntityType')

    entity_types = [
        {
            'name': 'site',
            'display_name': 'Site',
            'description': 'Construction site / worksite (tyomaa)',
            'icon': 'building-fill-gear',
        },
        {
            'name': 'equipment',
            'display_name': 'Equipment',
            'description': 'Machines, vehicles, equipment (kalusto)',
            'icon': 'truck',
        },
        {
            'name': 'drawing',
            'display_name': 'Drawing',
            'description': 'Technical drawing / plan (piirustus)',
            'icon': 'file-earmark-image',
        },
        {
            'name': 'material',
            'display_name': 'Material',
            'description': 'Construction material (materiaali)',
            'icon': 'box-seam',
        },
        {
            'name': 'inspection',
            'display_name': 'Inspection',
            'description': 'Quality inspection, TR-measurement (tarkastus)',
            'icon': 'clipboard-check',
        },
        {
            'name': 'observation',
            'display_name': 'Observation',
            'description': 'Site observation, quality issue (havainto)',
            'icon': 'eye',
        },
        {
            'name': 'schedule',
            'display_name': 'Schedule',
            'description': 'Project schedule / timeline (aikataulu)',
            'icon': 'calendar-week',
        },
        {
            'name': 'contractor',
            'display_name': 'Contractor',
            'description': 'Subcontractor / supplier (urakoitsija)',
            'icon': 'people',
        },
        {
            'name': 'worker',
            'display_name': 'Worker',
            'description': 'Site worker / employee (tyontekija)',
            'icon': 'person-badge',
        },
        {
            'name': 'model',
            'display_name': 'Model',
            'description': 'BIM model / 3D model (malli)',
            'icon': 'box',
        },
    ]

    for entity_type in entity_types:
        EntityType.objects.get_or_create(
            name=entity_type['name'],
            defaults=entity_type
        )


def reverse_seed_construction_entity_types(apps, schema_editor):
    """Remove construction industry entity types."""
    EntityType = apps.get_model('systems', 'EntityType')
    EntityType.objects.filter(name__in=[
        'site', 'equipment', 'drawing', 'material', 'inspection',
        'observation', 'schedule', 'contractor', 'worker', 'model'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0029_add_industry_template_models'),
    ]

    operations = [
        migrations.RunPython(
            seed_construction_entity_types,
            reverse_seed_construction_entity_types
        ),
    ]
