# Generated by Django 4.2 on 2026-02-15
# Data migration to seed construction industry template with Infrakit mappings

from django.db import migrations


def seed_construction_template(apps, schema_editor):
    """Create construction industry template with term and field mappings."""
    IndustryTemplate = apps.get_model('systems', 'IndustryTemplate')
    TermMapping = apps.get_model('systems', 'TermMapping')
    FieldMapping = apps.get_model('systems', 'FieldMapping')
    System = apps.get_model('systems', 'System')
    EntityType = apps.get_model('systems', 'EntityType')

    # Create the construction industry template
    template, created = IndustryTemplate.objects.get_or_create(
        name='construction',
        defaults={
            'display_name': 'Construction Industry',
            'description': 'Pre-configured mappings for construction industry systems including Infrakit, Congrid, Procore, and Visma.',
            'icon': 'building',
        }
    )

    # Get Infrakit system if it exists
    infrakit = System.objects.filter(alias='infrakit').first()
    if not infrakit:
        print("Infrakit system not found, skipping term/field mappings")
        return

    # =========================================================================
    # Term Mappings for Infrakit
    # =========================================================================
    term_mappings = [
        # Core construction terms
        ('project', 'Project'),
        ('site', 'Site'),
        ('equipment', 'Machine'),
        ('drawing', 'Model'),
        ('material', 'Material'),
        ('inspection', 'Logpoint'),  # As-built measurements
        ('observation', 'Logpoint'),
        ('schedule', 'Schedule'),
        ('contractor', 'Contractor'),
        ('worker', 'Worker'),
        ('model', 'Model'),
        ('folder', 'Folder'),
        ('document', 'Document'),
        ('organization', 'Organization'),
    ]

    for canonical_term, system_term in term_mappings:
        TermMapping.objects.get_or_create(
            template=template,
            canonical_term=canonical_term,
            system=infrakit,
            defaults={'system_term': system_term}
        )

    # =========================================================================
    # Field Mappings for Infrakit
    # =========================================================================
    # Get entity types
    project_type = EntityType.objects.filter(name='project').first()
    site_type = EntityType.objects.filter(name='site').first()
    equipment_type = EntityType.objects.filter(name='equipment').first()
    drawing_type = EntityType.objects.filter(name='drawing').first()
    material_type = EntityType.objects.filter(name='material').first()
    model_type = EntityType.objects.filter(name='model').first()

    if project_type:
        project_fields = [
            ('project_id', 'uuid', '', True, 'Unique project identifier'),
            ('project_name', 'name', '', True, 'Project name'),
            ('organization_id', 'organizationUuid', '', False, 'Organization UUID'),
            ('start_date', 'startDate', 'date_iso', False, 'Project start date'),
            ('end_date', 'endDate', 'date_iso', False, 'Project end date'),
            ('address', 'location.address', '', False, 'Project address'),
            ('latitude', 'location.latitude', '', False, 'Location latitude'),
            ('longitude', 'location.longitude', '', False, 'Location longitude'),
            ('area_m2', 'area', '', False, 'Project area in square meters'),
            ('status', 'status', '', False, 'Project status'),
        ]

        for canonical, system, transform, required, desc in project_fields:
            FieldMapping.objects.get_or_create(
                template=template,
                entity_type=project_type,
                canonical_field=canonical,
                system=infrakit,
                defaults={
                    'system_field': system,
                    'transform': transform,
                    'is_required': required,
                    'description': desc,
                }
            )

    if equipment_type:
        equipment_fields = [
            ('equipment_id', 'uuid', '', True, 'Unique equipment identifier'),
            ('equipment_name', 'name', '', True, 'Equipment name'),
            ('equipment_type', 'type', '', False, 'Equipment type (excavator, truck, etc.)'),
            ('status', 'status', '', False, 'Equipment status'),
            ('location', 'location', '', False, 'Current location'),
        ]

        for canonical, system, transform, required, desc in equipment_fields:
            FieldMapping.objects.get_or_create(
                template=template,
                entity_type=equipment_type,
                canonical_field=canonical,
                system=infrakit,
                defaults={
                    'system_field': system,
                    'transform': transform,
                    'is_required': required,
                    'description': desc,
                }
            )

    if model_type or drawing_type:
        entity = model_type or drawing_type
        model_fields = [
            ('model_id', 'uuid', '', True, 'Unique model identifier'),
            ('model_name', 'name', '', True, 'Model/drawing name'),
            ('folder_id', 'folderUuid', '', False, 'Parent folder UUID'),
            ('file_type', 'fileType', '', False, 'File type'),
            ('version', 'version', '', False, 'Model version'),
            ('uploaded_at', 'uploadedAt', 'datetime_iso', False, 'Upload timestamp'),
        ]

        for canonical, system, transform, required, desc in model_fields:
            FieldMapping.objects.get_or_create(
                template=template,
                entity_type=entity,
                canonical_field=canonical,
                system=infrakit,
                defaults={
                    'system_field': system,
                    'transform': transform,
                    'is_required': required,
                    'description': desc,
                }
            )

    if material_type:
        material_fields = [
            ('material_id', 'uuid', '', True, 'Unique material identifier'),
            ('material_name', 'name', '', True, 'Material name'),
            ('material_type', 'type', '', False, 'Material type'),
            ('unit', 'unit', '', False, 'Unit of measurement'),
            ('quantity', 'quantity', '', False, 'Quantity'),
        ]

        for canonical, system, transform, required, desc in material_fields:
            FieldMapping.objects.get_or_create(
                template=template,
                entity_type=material_type,
                canonical_field=canonical,
                system=infrakit,
                defaults={
                    'system_field': system,
                    'transform': transform,
                    'is_required': required,
                    'description': desc,
                }
            )


def reverse_seed_construction_template(apps, schema_editor):
    """Remove construction industry template."""
    IndustryTemplate = apps.get_model('systems', 'IndustryTemplate')
    IndustryTemplate.objects.filter(name='construction').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0030_seed_construction_entity_types'),
    ]

    operations = [
        migrations.RunPython(
            seed_construction_template,
            reverse_seed_construction_template
        ),
    ]
