# Generated by Django 4.2 on 2026-02-15
# Migration to add industry field to System model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0031_seed_construction_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='industry',
            field=models.ForeignKey(
                blank=True,
                help_text='Industry category this system belongs to (e.g., construction, energy)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='systems',
                to='systems.industrytemplate'
            ),
        ),
    ]
