# Generated by Django 4.2 on 2026-02-15
# Migration to add GraphQL support: graphql_schema field to Interface model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0035_add_scheduling_and_monitoring_adapters'),
    ]

    operations = [
        # Add graphql_schema JSONField to Interface model
        migrations.AddField(
            model_name='interface',
            name='graphql_schema',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Cached GraphQL introspection schema (for GRAPHQL type interfaces)'
            ),
        ),
    ]
