# Generated by Django 5.2.10 on 2026-02-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0036_add_graphql_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='type',
            field=models.CharField(choices=[('API', 'API'), ('GRAPHQL', 'GraphQL'), ('XHR', 'XHR')], max_length=8),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_type',
            field=models.CharField(choices=[('project_management', 'Project Management'), ('communication', 'Communication'), ('version_control', 'Version Control'), ('ci_cd', 'CI/CD'), ('monitoring', 'Monitoring'), ('storage', 'Storage'), ('quality_management', 'Quality Management'), ('erp', 'ERP / Finance'), ('bim', 'BIM / Design'), ('other', 'Other')], max_length=50),
        ),
    ]
