# Generated by Django 5.2.10 on 2026-02-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0041_add_sitedrive_and_takting'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the system was first confirmed working', null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='True when system has been tested with a working integration'),
        ),
    ]
