# Generated by Django 5.2.10 on 2026-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0043_add_global_construction_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='alias',
            field=models.CharField(help_text="Unique alias used in tool names (e.g., 'jira', 'slack')", max_length=50, unique=True),
        ),
    ]
