# Generated by Django 5.2.10 on 2026-02-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0013_remove_data_mappings'),
        ('systems', '0045_accountsystem_project_scoping'),
    ]

    operations = [
        # Clear unique_together BEFORE removing fields (required for SQLite)
        migrations.AlterUniqueTogether(
            name='systementityidentifier',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='fieldmapping',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='termmapping',
            unique_together=None,
        ),
        # Remove FK fields
        migrations.RemoveField(
            model_name='systementityidentifier',
            name='mapping',
        ),
        migrations.RemoveField(
            model_name='systementityidentifier',
            name='system',
        ),
        migrations.RemoveField(
            model_name='fieldmapping',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='fieldmapping',
            name='system',
        ),
        migrations.RemoveField(
            model_name='fieldmapping',
            name='template',
        ),
        migrations.RemoveField(
            model_name='termmapping',
            name='template',
        ),
        migrations.RemoveField(
            model_name='termmapping',
            name='system',
        ),
        migrations.RemoveField(
            model_name='system',
            name='industry',
        ),
        # Delete models
        migrations.DeleteModel(
            name='EntityMapping',
        ),
        migrations.DeleteModel(
            name='EntityType',
        ),
        migrations.DeleteModel(
            name='FieldMapping',
        ),
        migrations.DeleteModel(
            name='IndustryTemplate',
        ),
        migrations.DeleteModel(
            name='SystemEntityIdentifier',
        ),
        migrations.DeleteModel(
            name='TermMapping',
        ),
    ]
