# Generated by Django 5.2.11 on 2026-03-05 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_unique_active_account_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('client_secret_hash', models.CharField(max_length=128)),
                ('client_secret_prefix', models.CharField(max_length=10)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('mode', models.CharField(choices=[('safe', 'Safe Mode'), ('power', 'Power Mode')], default='safe', help_text='Default mode for API keys created via this OAuth app.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Account whose API keys will be created on token exchange.', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_applications', to='accounts.account')),
            ],
            options={
                'verbose_name': 'OAuth Application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=128, unique=True)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('state', models.CharField(blank=True, max_length=500)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='oauth.oauthapplication')),
            ],
            options={
                'verbose_name': 'Authorization Code',
                'ordering': ['-created_at'],
            },
        ),
    ]
