# Generated by Django 5.2.11 on 2026-03-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0018_alter_agentprofile_include_tools'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthapplication',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Agent profile for tokens. If set, overrides mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_applications', to='mcp.agentprofile'),
        ),
        migrations.AddField(
            model_name='oauthapplication',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project to bind tokens to. If empty, uses account default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_applications', to='mcp.project'),
        ),
        migrations.AlterField(
            model_name='oauthapplication',
            name='mode',
            field=models.CharField(choices=[('safe', 'Safe Mode'), ('power', 'Power Mode')], default='safe', help_text='Default mode for API keys (used only if no profile is set).', max_length=20),
        ),
    ]
